sudo: required

os: linux

# CI runs over all branches that do not contain 'ros1' in the name
branches:
  except:
  - /.*ros1.*/

env:
  global:
    - CCACHE_DIR=${HOME}/.ccache
    - BUILD="mkdir -p ~/colcon_ws/src; cd ~/colcon_ws; ln -s ${TRAVIS_BUILD_DIR} src/px4_msgs; colcon build --cmake-args --symlink-install --event-handlers console_direct+"

language: cpp

cache: ccache

services: docker

matrix:
  include:
    - name: Build on ROS2 Ardent
      env:
        - ROS2_DISTRO=ardent
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-ardent:2020-06-27
    - name: Build on ROS2 Bouncy
      env:
        - ROS2_DISTRO=bouncy
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-bouncy:2020-06-27
    - name: Build on ROS2 Crystal
      env:
        - ROS2_DISTRO=crystal
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-crystal:2020-06-27
    - name: Build on ROS2 Dashing
      env:
        - ROS2_DISTRO=dashing
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-dashing:2020-06-27
    - name: Build on ROS2 Eloquent
      env:
        - ROS2_DISTRO=eloquent
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-eloquent:2020-06-27
    - name: Build on ROS2 Foxy
      env:
        - ROS2_DISTRO=foxy
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-foxy:2020-06-27

script:
  - docker run -it --rm -w ${TRAVIS_BUILD_DIR}
    --name=px4_ros2_container
    --env=CCACHE_DIR="${CCACHE_DIR}"
    --env=LOCAL_USER_ID="$(id -u)"
    --volume=${CCACHE_DIR}:${CCACHE_DIR}:rw
    --volume=${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}:rw
    ${DOCKER_CONTAINER} /bin/bash -ce "source ${ROS2_ENV}; ${BUILD}";
