sudo: required

# CI runs over all branches that do not contain 'ros1' in the name
branches:
  except:
  - /.*ros1.*/

env:
  global:
    - CCACHE_DIR=${HOME}/.ccache
    - BUILD="mkdir -p ~/colcon_ws/src; cd ~/colcon_ws; ln -s ${TRAVIS_BUILD_DIR} src/px4_msgs; colcon build --cmake-args --symlink-install --event-handlers console_direct+"

matrix:
  include:
    - name: Build on ROS2 Ardent
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS2_DISTRO=ardent
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-ardent:2020-03-16
    - name: Build on ROS2 Bouncy
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS2_DISTRO=bouncy
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-bouncy:2020-03-16
    - name: Build on ROS2 Crystal
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS2_DISTRO=crystal
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-crystal:2020-03-16
    - name: Build on ROS2 Dashing
      os: linux
      language: cpp
      services:
        - docker
      cache:
      ccache: true
      env:
        - ROS2_DISTRO=dashing
        - ROS2_ENV=/opt/ros/${ROS2_DISTRO}/setup.bash
        - DOCKER_CONTAINER=px4io/px4-dev-ros2-dashing:2020-03-16

script:
  - docker run -it --rm -w ${TRAVIS_BUILD_DIR}
    --name=px4_ros2_container
    --env=CCACHE_DIR="${CCACHE_DIR}"
    --env=LOCAL_USER_ID="$(id -u)"
    --volume=${CCACHE_DIR}:${CCACHE_DIR}:rw
    --volume=${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR}:rw
    ${DOCKER_CONTAINER} /bin/bash -ce "source ${ROS2_ENV}; ${BUILD}";
